### ISSUE TITLE
The function reference page cannot open properly

### ISSUE THREAD

**Issue by yufenhuang** [mocaptoolbox/mocaptoolbox#1]
The page '4. Function Reference' cannot open properly. The error message is 'The wiki page took too long to render. This wiki page's content is too large to render on this page.'

Thank you!

**Comment by mocaptoolbox** [comment]
Thanks @yufenhuang. Did you try refreshing the page? I would say that this is more of a Github problem...

**Comment by mocaptoolbox** [comment]
@yufenhuang, I have condensed the contents of the function reference page as a workaround. It is not yet the perfect solution; I sometimes get the error but GitHub displays the page when I refresh it.

**Comment by mocaptoolbox** [comment]
@yufenhuang it seems that this was a Github problem that has been resolved. I have not been experiencing this issue lately even though the function reference page has been expanding over recent months.
