### ISSUE TITLE
mcboudrect: consider always a frequency of 120Hz

### ISSUE THREAD

**Issue by deninom** [mocaptoolbox/mocaptoolbox#4]
The following lines must be replaced to use the right frequency:
%REPLACE       for b=0:hop:(d.nFrames/120)-w
%WITH
        for b=0:hop:(double(d.nFrames)/d.freq)-w
%REPLACE     ind1=1+120*b;
 %WITH
           ind1=1+d.freq * b;
%REPLACE            ind2=min(size(d.data,1), ind1+120 * w);
  %WITH
           ind2=min(size(d.data,1), ind1+d.freq * w);

**Comment by mocaptoolbox** [comment]
Thanks @deninom for your bug reports and fixes!
